### ISSUE TITLE
Django 3 issues: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by aerasoft** [jazzband/django-robots#96]
https://github.com/jazzband/django-robots/blob/master/robots/models.py#L5

Can the code be updated to import correctly?

**Comment by danihodovic** [comment]
@nautatva ?

**Comment by nautatva** [comment]
Did you install the python package six? The automated builds are also passing, so there shouldn't be any errors.
https://pypi.org/project/six/

**Comment by timmyomahony** [comment]
I'm also seeing this error (Python 3.7.6):

```
Django==3.0.1
django-robots==3.1.0
six==1.13.0
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/robots/models.py", line 3, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/timmyomahony/.virtualenvs/timmy-omahony/lib/python3.7/site-packages/django/utils/encoding.py)
```

**Comment by danihodovic** [comment]
The most recent version has not been released on pypi.

```
$ pip install django-robots==
Collecting django-robots==
  Could not find a version that satisfies the requirement django-robots== (from versions: 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.9, 0.9.1, 0.9.2, 1.0, 1.1, 2.0rc1, 2.0rc2, 2.0rc3, 2.0rc4, 2.0, 3.0rc1, 3.0, 3.1.0)
No matching distribution found for django-robots==
```

**Comment by nautatva** [comment]
Thanks for noting, I just released the new version on Pypi, consider updating the requirements to ``django-robots==3.2.0``

**Comment by danihodovic** [comment]
Thanks @nautatva

**Comment by danihodovic** [comment]
The latest version is still 3.1.0

![image](https://user-images.githubusercontent.com/5557301/71747234-67721a00-2e6f-11ea-8875-e201b08f5683.png)

**Comment by nautatva** [comment]
The semi-automated Pypi releases are failing. Please look into it @jezdez.

<img width="963" alt="Screenshot 2020-01-04 at 7 17 22 PM" src="https://user-images.githubusercontent.com/28155271/71766544-f5f5a280-2f26-11ea-8ae7-63810d258f43.png">

@danihodovic use the master branch instead of using pip as of now.

**Comment by jezdez** [comment]
Hey there, release failed to PyPI with this error:

```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/ 
```

This is what needs to happen to fix this:

- [ ] Please add a new test using [`twine check`](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup) which will make sure this won't happen again.
- [ ] Fix the rST formatting issue, push the change to the repo.
- [ ] Delete the existing Git tag locally and on GitHub and redo it with the latest commit.

**Comment by jezdez** [comment]
@nautatva I forgot to upload the already existing files before you did the new release, sorry!

I'll redo all of this now.

**Comment by nautatva** [comment]
Made a mess in commits, I'll squash them for a better history

**Comment by jezdez** [comment]
@nautatva Next time please let's work on this in a PR first, ok?

**Comment by nautatva** [comment]
Sure

**Comment by jezdez** [comment]
[4.0](https://github.com/jazzband/django-robots/releases/tag/4.0) is out now: https://pypi.org/project/django-robots/.

**Comment by bcyoungV** [comment]
Il fait quoi django-robts j'ai pas bien compris
